export const COUNTRIES_AND_CURRENCIES: Record<string, string> = {
  "Afghanistan": "؋",
  "Albania": "L",
  "Algeria": "د.ج",
  "Andorra": "€",
  "Angola": "Kz",
  "Antigua and Barbuda": "$",
  "Argentina": "$",
  "Armenia": "֏",
  "Australia": "$",
  "Austria": "€",
  "Azerbaijan": "₼",
  "Bahamas": "$",
  "Bahrain": ".د.ب",
  "Bangladesh": "৳",
  "Barbados": "$",
  "Belarus": "Br",
  "Belgium": "€",
  "Belize": "$",
  "Benin": "CFA",
  "Bhutan": "Nu.",
  "Bolivia": "Bs.",
  "Bosnia and Herzegovina": "KM",
  "Botswana": "P",
  "Brazil": "R$",
  "Brunei": "$",
  "Bulgaria": "лв",
  "Burkina Faso": "CFA",
  "Burundi": "FBu",
  "Cabo Verde": "$",
  "Cambodia": "៛",
  "Cameroon": "CFA",
  "Canada": "$",
  "Central African Republic": "CFA",
  "Chad": "CFA",
  "Chile": "$",
  "China": "¥",
  "Colombia": "$",
  "Comoros": "CF",
  "Congo (Congo-Brazzaville)": "CFA",
  "Costa Rica": "₡",
  "Croatia": "€",
  "Cuba": "₱",
  "Cyprus": "€",
  "Czechia (Czech Republic)": "Kč",
  "Democratic Republic of the Congo": "FC",
  "Denmark": "kr",
  "Djibouti": "Fdj",
  "Dominica": "$",
  "Dominican Republic": "RD$",
  "Ecuador": "$",
  "Egypt": "£",
  "El Salvador": "$",
  "Equatorial Guinea": "CFA",
  "Eritrea": "Nfk",
  "Estonia": "€",
  "Eswatini (fmr. Swaziland)": "L",
  "Ethiopia": "Br",
  "Fiji": "$",
  "Finland": "€",
  "France": "€",
  "Gabon": "CFA",
  "Gambia": "D",
  "Georgia": "₾",
  "Germany": "€",
  "Ghana": "₵",
  "Greece": "€",
  "Grenada": "$",
  "Guatemala": "Q",
  "Guinea": "FG",
  "Guinea-Bissau": "CFA",
  "Guyana": "$",
  "Haiti": "G",
  "Honduras": "L",
  "Hungary": "Ft",
  "Iceland": "kr",
  "India": "₹",
  "Indonesia": "Rp",
  "Iran": "﷼",
  "Iraq": "ع.د",
  "Ireland": "€",
  "Israel": "₪",
  "Italy": "€",
  "Jamaica": "J$",
  "Japan": "¥",
  "Jordan": "د.ا",
  "Kazakhstan": "₸",
  "Kenya": "KSh",
  "Kiribati": "$",
  "Kuwait": "د.ك",
  "Kyrgyzstan": "лв",
  "Laos": "₭",
  "Latvia": "€",
  "Lebanon": "£",
  "Lesotho": "L",
  "Liberia": "$",
  "Libya": "ل.د",
  "Liechtenstein": "Fr",
  "Lithuania": "€",
  "Luxembourg": "€",
  "Madagascar": "Ar",
  "Malawi": "MK",
  "Malaysia": "RM",
  "Maldives": "Rf",
  "Mali": "CFA",
  "Malta": "€",
  "Marshall Islands": "$",
  "Mauritania": "UM",
  "Mauritius": "₨",
  "Mexico": "$",
  "Micronesia": "$",
  "Moldova": "L",
  "Monaco": "€",
  "Mongolia": "₮",
  "Montenegro": "€",
  "Morocco": "د.م.",
  "Mozambique": "MT",
  "Myanmar (formerly Burma)": "K",
  "Namibia": "$",
  "Nauru": "$",
  "Nepal": "₨",
  "Netherlands": "€",
  "New Zealand": "$",
  "Nicaragua": "C$",
  "Niger": "CFA",
  "Nigeria": "₦",
  "North Korea": "₩",
  "North Macedonia": "ден",
  "Norway": "kr",
  "Oman": "ر.ع.",
  "Pakistan": "₨",
  "Palau": "$",
  "Palestine State": "₪",
  "Panama": "B/.",
  "Papua New Guinea": "K",
  "Paraguay": "Gs",
  "Peru": "S/.",
  "Philippines": "₱",
  "Poland": "zł",
  "Portugal": "€",
  "Qatar": "ر.ق",
  "Romania": "lei",
  "Russia": "₽",
  "Rwanda": "FRw",
  "Saint Kitts and Nevis": "$",
  "Saint Lucia": "$",
  "Saint Vincent and the Grenadines": "$",
  "Samoa": "WS$",
  "San Marino": "€",
  "Sao Tome and Principe": "Db",
  "Saudi Arabia": "﷼",
  "Senegal": "CFA",
  "Serbia": "Дин.",
  "Seychelles": "₨",
  "Sierra Leone": "Le",
  "Singapore": "$",
  "Slovakia": "€",
  "Slovenia": "€",
  "Solomon Islands": "$",
  "Somalia": "S",
  "South Africa": "R",
  "South Korea": "₩",
  "South Sudan": "£",
  "Spain": "€",
  "Sri Lanka": "₨",
  "Sudan": "£",
  "Suriname": "$",
  "Sweden": "kr",
  "Switzerland": "Fr",
  "Syria": "£",
  "Tajikistan": "ЅМ",
  "Tanzania": "TSh",
  "Thailand": "฿",
  "Timor-Leste": "$",
  "Togo": "CFA",
  "Tonga": "T$",
  "Trinidad and Tobago": "TT$",
  "Tunisia": "د.ت",
  "Turkey": "₺",
  "Turkmenistan": "T",
  "Tuvalu": "$",
  "Uganda": "USh",
  "Ukraine": "₴",
  "United Arab Emirates": "د.إ",
  "United Kingdom": "£",
  "United States of America": "$",
  "Uruguay": "$U",
  "Uzbekistan": "лв",
  "Vanuatu": "VT",
  "Venezuela": "Bs",
  "Vietnam": "₫",
  "Yemen": "﷼",
  "Zambia": "ZK",
  "Zimbabwe": "$"
};

export const COUNTRIES = Object.keys(COUNTRIES_AND_CURRENCIES);
